# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Approve Dependabot'

on:
  pull_request_target:
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    uses: ./.github/workflows/approve-dependabot.yml
    secrets: inherit
