# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approvals.'

on:
  pull_request_target:

jobs:
  dependabot:
    permissions:
      pull-requests: write
      contents: write

    runs-on: [ ubuntu-latest ]
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: |
      github.actor == 'dependabot[bot]'
    steps:
      # The real protection is in dependabot configuration and that the repo
      # builds, runs tests and they succeed.
      - name: Approve a PR & mark for auto apply.
        run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
