# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
# @example=## Golang Automatic Patch Releaser Sample
## SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
#---
#name: 'Automatically relase patch versions.'
#
#  on:
#    schedule: # Run every day at 12:00 UTC
#      - cron: '0 12 * * *'
#    workflow_dispatch:
#
#  jobs:
#    release:
#      uses: xmidt-org/shared-go/.github/workflows/ci.yml@826aa545bb56f6c7c551d44febb420c0293c8bff # v4.2.0
#      secrets: inherit
---
name: 'Auto Releaser'

on:
  workflow_call:
    inputs:

      branch:
        description: 'Branch to release from.'
        type: string
        required: false
        default: 'main'

      patch-list:
        description: 'Comma separated list of commit types that should trigger a patch release.'
        type: string
        required: false
        default: fix, Fix, FIX, bugfix, Bugfix, BugFix, BUGFIX, perf, refactor, Refactor, REFACTOR, test, Test, TEST, tests, Tests, TESTS, chore, Chore, CHORE

      minor-list:
        description: 'The specific minor prefix names to use for minors.'
        type: string
        required: false
        default: feat, Feat, FEAT, feature, Feature, FEATURE

      which:
        description: Create a 'release' or 'tag'.
        type: string
        required: false
        default: tag

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@d93d5fbbab3c2e2ec76b0d22abac50e8e853fcd2 # v1.10.0
        with:
          token:                 ${{ github.token }}
          branch:                ${{ inputs.branch }}
          patchList:             ${{ inputs.patch-list }}
          minorList:             ${{ inputs.minor-list }}
          noVersionBumpBehavior: silent
          noNewCommitBehavior:   silent

      - name: No Release Needed
        if: |
          steps.semver.outputs.next == ''
        run: echo "No release needed."

      - name: Create Release
        if: |
          steps.semver.outputs.next != '' &&
          inputs.which == 'release'
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          name:   ${{ steps.semver.outputs.next }}
          tag:    ${{ steps.semver.outputs.next }}
          commit: ${{ github.sha }}
          token:  ${{ github.token }}

      - name: Create Tag
        if: |
          steps.semver.outputs.next != '' &&
          inputs.which == 'tag'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.next }}',
              sha: context.sha
            })

      - name: Failure
        if: |
          steps.semver.outputs.next != '' &&
          inputs.which != 'release' &&
          inputs.which != 'tag'
        run: |
          echo "No new version found."
          exit
