# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
# @example=## Golang Automatic Patch Releaser Sample
## SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
#---
#name: 'Automatically relase patch versions.'
#  
#  on:
#    schedule: # Run every day at 12:00 UTC
#      - cron: '0 12 * * *'
#    workflow_dispatch:
#  
#  jobs:
#    release:
#      uses: xmidt-org/shared-go/.github/workflows/ci.yml@826aa545bb56f6c7c551d44febb420c0293c8bff # v4.2.0
---
name: 'Auto Releaser'

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to release from.'
        type: string
        required: false
        default: 'main'
      patch-list:
        description: 'Comma separated list of commit types that should trigger a patch release.'
        type: string
        required: false
        default: 'fix, bugfix, perf, refactor, test, tests, chore'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@2415a9e79db34eb828a8dc1d20d4890725737227 # v1.8.0
        with:
          token:                 ${{ github.token }}
          branch:                ${{ inputs.branch }}
          patchList:             ${{ inputs.patch-list }}
          noVersionBumpBehavior: silent
          noNewCommitBehavior:   silent

      - name: No Release Needed
        if: |
          steps.semver.outputs.next == ''
        run: echo "No release needed."

      - name: Create Release
        if: |
          steps.semver.outputs.next != ''
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          name:   ${{ steps.semver.outputs.next }}
          tag:    ${{ steps.semver.outputs.next }}
          commit: ${{ github.sha }}
          token:  ${{ github.token }}
