# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
on:
  push:
    branches:
      - 'main'
    paths:
      - README.md

jobs:
  done:
    runs-on: [ ubuntu-latest ]
    steps:
      - run: echo "No tests to run, but satify the branch rule."