# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

# @example=## Project Tracking
## SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
#---
#name: 'Project Tracking'
#
#on:
#  issues:
#    types:
#      - opened
#  pull_request:
#    types:
#      - opened
#
#jobs:
#  project:
#    uses: xmidt-org/shared-go/.github/workflows/proj.yml@6a0bec30f42c318c0c1d06705f3f60911ed7c610 # v3.2.0
#    secrets: inherit
---
name: 'Project Tracking Workflow'

on:
  workflow_call:

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      # Target the team project board.
      - uses: actions/add-to-project@9bfe908f2eaa7ba10340b31e314148fcfe6a2458 # v1.0.1
        with:
          project-url: https://github.com/orgs/comcast-cl/projects/3
          github-token: ${{ secrets.PROJECT_ISSUE_CREATION_TOKEN }}
